User.create!(name:  "管理者",
             email: "sample@email.com",
             affiliation: "管理部",
             employee_number: 1,
             uid: 999,
             password:              "password",
             password_confirmation: "password",
             basic_work_time: Time.zone.parse('2019-07-01 07:30:00'),
             designated_work_start_time: Time.current.change(hour: 9, min: 0, sec: 0),
             designated_work_end_time: Time.current.change(hour: 18, min: 0, sec: 0),
             admin: true)

User.create!(name:  "上長A",
             email: "superior1@email.com",
             affiliation: "エンジニアリング事業部",
             employee_number: 2,
             uid: 1000,
             password:              "password",
             password_confirmation: "password",
             basic_work_time: Time.zone.parse('2019-07-01 07:30:00'),
             designated_work_start_time: Time.current.change(hour: 9, min: 0, sec: 0),
             designated_work_end_time: Time.current.change(hour: 18, min: 0, sec: 0),
             superior: true)
             
User.create!(name:  "上長B",
             email: "superior2@email.com",
             affiliation: "フリーランス事業部",
             employee_number: 3,
             uid: 1001,
             password:              "password",
             password_confirmation: "password",
             basic_work_time: Time.zone.parse('2019-07-01 07:30:00'),
             designated_work_start_time: Time.current.change(hour: 9, min: 0, sec: 0),
             designated_work_end_time: Time.current.change(hour: 18, min: 0, sec: 0),
             superior: true)

User.create!(name:  "上長C",
             email: "superior3@email.com",
             affiliation: "フリーランス事業部",
             employee_number: 4,
             uid: 1002,
             password:              "password",
             password_confirmation: "password",
             basic_work_time: Time.zone.parse('2019-07-01 07:30:00'),
             designated_work_start_time: Time.current.change(hour: 9, min: 0, sec: 0),
             designated_work_end_time: Time.current.change(hour: 18, min: 0, sec: 0),
             superior: true)

User.create!(name:  "齋藤隼人",
             email: "hayato@email.com",
             affiliation: "フリーランス事業部",
             employee_number: 4,
             uid: 1002,
             password:              "password",
             password_confirmation: "password",
             basic_work_time: Time.zone.parse('2019-07-01 07:30:00'),
             designated_work_start_time: Time.current.change(hour: 9, min: 0, sec: 0),
             designated_work_end_time: Time.current.change(hour: 18, min: 0, sec: 0))
